import 'dart:io';
import 'package:doctor_hunt/data/models/decoder_response_model.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class DecoderPdfGenerator {
  DecoderPdfGenerator._();

  static Future<File> generateAndSave(DecoderAnalysis analysis) async {
    final pdf = _buildPdf(analysis);
    final bytes = await pdf.save();

    final directory = await getApplicationDocumentsDirectory();
    final dateStamp = DateFormat('yyyy-MM-dd_HHmmss').format(DateTime.now());
    final filePath = '${directory.path}/medical_analysis_$dateStamp.pdf';

    final file = File(filePath);
    await file.writeAsBytes(bytes);
    return file;
  }

  static pw.Document _buildPdf(DecoderAnalysis analysis) {
    final pdf = pw.Document(
      title: 'Medical Document Analysis',
      author: 'Doctor Hunt',
    );

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(48),
        header: (context) => _buildHeader(analysis),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          _buildSummarySection(analysis),
          if (analysis.medications.isNotEmpty)
            _buildMedicationsSection(analysis),
          if (analysis.labFindings.isNotEmpty)
            _buildLabFindingsSection(analysis),
          if (analysis.keyFindings.isNotEmpty)
            _buildKeyFindingsSection(analysis),
        ],
      ),
    );

    return pdf;
  }

  static pw.Widget _buildHeader(DecoderAnalysis analysis) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 16),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(width: 1, color: PdfColors.grey400),
        ),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'Doctor Hunt',
                style: const pw.TextStyle(
                  fontSize: 14,
                  color: PdfColors.grey600,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.Text(
                'Document Decoder Analysis',
                style: const pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey500,
                ),
              ),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text(
                analysis.documentTypeLabel,
                style: const pw.TextStyle(
                  fontSize: 12,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.teal700,
                ),
              ),
              pw.Text(
                DateFormat('dd MMM yyyy').format(DateTime.now()),
                style: const pw.TextStyle(
                  fontSize: 9,
                  color: PdfColors.grey500,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildFooter(pw.Context context) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 12),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          top: pw.BorderSide(width: 0.5, color: PdfColors.grey300),
        ),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Generated by Doctor Hunt Document Decoder',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey400),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey400),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildSummarySection(DecoderAnalysis analysis) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Summary'),
        pw.SizedBox(height: 6),
        pw.Text(
          analysis.summary,
          style: const pw.TextStyle(fontSize: 11, lineSpacing: 4),
        ),
      ],
    );
  }

  static pw.Widget _buildMedicationsSection(DecoderAnalysis analysis) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Medications'),
        pw.SizedBox(height: 6),
        ...analysis.medications.map(_buildMedicationBlock),
      ],
    );
  }

  static pw.Widget _buildMedicationBlock(DecodedMedication med) {
    final rows = <pw.Widget>[
      pw.Text(
        med.name,
        style: const pw.TextStyle(
          fontSize: 12,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.teal800,
        ),
      ),
    ];

    if (med.purpose.isNotEmpty) {
      rows.add(_detailLine('Purpose', med.purpose));
    }
    if (med.dosage.isNotEmpty) {
      rows.add(_detailLine('Dosage', med.dosage));
    }
    if (med.frequency.isNotEmpty) {
      rows.add(_detailLine('Frequency', med.frequency));
    }
    if (med.duration.isNotEmpty) {
      rows.add(_detailLine('Duration', med.duration));
    }
    if (med.instructions.isNotEmpty) {
      rows.add(_detailLine('Instructions', med.instructions));
    }

    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 10),
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300, width: 0.5),
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: rows,
      ),
    );
  }

  static pw.Widget _buildLabFindingsSection(DecoderAnalysis analysis) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Lab Findings'),
        pw.SizedBox(height: 6),
        pw.TableHelper.fromTextArray(
          headerStyle: const pw.TextStyle(
            fontSize: 10,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.white,
          ),
          headerDecoration: const pw.BoxDecoration(
            color: PdfColors.teal700,
            borderRadius: pw.BorderRadius.only(
              topLeft: pw.Radius.circular(4),
              topRight: pw.Radius.circular(4),
            ),
          ),
          cellStyle: const pw.TextStyle(fontSize: 9, lineSpacing: 2),
          cellAlignment: pw.Alignment.centerLeft,
          cellPadding: const pw.EdgeInsets.symmetric(
            horizontal: 8,
            vertical: 6,
          ),
          headerPadding: const pw.EdgeInsets.symmetric(
            horizontal: 8,
            vertical: 6,
          ),
          headers: ['Test', 'Result', 'Reference Range', 'Interpretation'],
          data: analysis.labFindings
              .map(
                (f) => [
                  f.testName,
                  f.displayValue + (f.isOutOfRange ? ' *' : ''),
                  f.referenceRange.isNotEmpty ? f.referenceRange : '—',
                  f.interpretation.isNotEmpty ? f.interpretation : '—',
                ],
              )
              .toList(),
        ),
      ],
    );
  }

  static pw.Widget _buildKeyFindingsSection(DecoderAnalysis analysis) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Key Findings'),
        pw.SizedBox(height: 4),
        ...analysis.keyFindings.map(
          (finding) => pw.Padding(
            padding: const pw.EdgeInsets.only(bottom: 4),
            child: pw.Text(
              '• $finding',
              style: const pw.TextStyle(fontSize: 10, lineSpacing: 3),
            ),
          ),
        ),
      ],
    );
  }

  static pw.Widget _sectionTitle(String title) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(top: 16, bottom: 2),
      child: pw.Text(
        title,
        style: const pw.TextStyle(
          fontSize: 14,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.grey800,
        ),
      ),
    );
  }

  static pw.Widget _detailLine(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(top: 2),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(
            width: 80,
            child: pw.Text(
              '$label:',
              style: const pw.TextStyle(
                fontSize: 10,
                color: PdfColors.grey600,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.Expanded(
            child: pw.Text(value, style: const pw.TextStyle(fontSize: 10)),
          ),
        ],
      ),
    );
  }
}
